# Generated by Django 4.2.16 on 2025-02-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentalpost',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
