# Generated by Django 4.2.16 on 2025-02-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_img/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
